### ISSUE TITLE
Roof & Mining Overlay Shaders

### ISSUE THREAD

**Issue by ghost** [FluffierThanThou/AreaUnlocker#3]
After enabling this mod, the roof and mining overlays lose their normal green coloration, and turn into a solid purple cover.  In the log, the following message is displayed:

```
-------- Shader compilation failed
#version 150
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shader_bit_encoding : enable
uniform 	vec4 hlslcc_mtx4x4unity_ObjectToWorld[4];
uniform 	vec4 hlslcc_mtx4x4unity_MatrixVP[4];
uniform 	vec4 __ST;
in  vec3 in_POSITION0;
in  vec4 in_COLOR0;
in  vec3 in_TEXCOORD0;
out vec4 vs_COLOR0;
out vec2 vs_TEXCOORD0;
vec4 u_xlat0;
vec4 u_xlat1;
void main()
{
    vs_COLOR0 = in_COLOR0;
    vs_COLOR0 = clamp(vs_COLOR0, 0.0, 1.0);
    vs_TEXCOORD0.xy = in_TEXCOORD0.xy * __ST.xy + __ST.zw;
    u_xlat0 = in_POSITION0.yyyy * hlslcc_mtx4x4unity_ObjectToWorld[1];
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[0] * in_POSITION0.xxxx + u_xlat0;
    u_xlat0 = hlslcc_mtx4x4unity_ObjectToWorld[2] * in_POSITION0.zzzz + u_xlat0;
    u_xlat0 = u_xlat0 + hlslcc_mtx4x4unity_ObjectToWorld[3];
    u_xlat1 = u_xlat0.yyyy * hlslcc_mtx4x4unity_MatrixVP[1];
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[0] * u_xlat0.xxxx + u_xlat1;
    u_xlat1 = hlslcc_mtx4x4unity_MatrixVP[2] * u_xlat0.zzzz + u_xlat1;
    gl_Position = hlslcc_mtx4x4unity_MatrixVP[3] * u_xlat0.wwww + u_xlat1;
    return;
}
-------- failed compiling:
vertex shader
0(7) : error C7528: OpenGL reserves names containing '__'

Note: Creation of internal variant of shader 'Custom/Vertex Color' failed.
WARNING: Shader Unsupported: 'Custom/Vertex Color' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Custom/Vertex Color' - Setting to default shader.
```

I have attached the full log for more detail, but after about 20 minutes of trial and error, I have narrowed down the source of the problem to the Area Unlocker mod.

For reference, I am playing Rimworld on Gentoo Linux, with the latest nVidia driver (387.22).

[rimworld_log.txt](https://github.com/FluffierThanThou/AreaUnlocker/files/1503348/rimworld_log.txt)

**Comment by FluffierThanThou** [comment]
but... but... this mod has literally nothing to do with any of that? 

Ugh.. I've had some scattered reports about the temperature overlay before, so it seems there might actually be something to it. I'll see if I can figure this one out, but it might be a little bit beyond my abilities.

**Comment by ghost** [comment]
Actually, I'm gonna close this bug.  Turns out the problem happened with vanilla Rimworld as well, but for some reason, it did seem to respond to the presence of area unlocker at one point.  I apologize for bugging you. :-/

**Comment by FluffierThanThou** [comment]
No worries, thanks for following up!
